window.lessonData = [
    { title: "1", chars: "诗碧妆绿丝剪童归" },
    { title: "2", chars: "冲寻眉吐闻柳荡桃" },
    { title: "3", chars: "鲜原叔通巧惊礼" },
    { title: "4", chars: "邓植格引注满" },
    { title: "语文园地一", chars: "剧场" },
    { title: "5", chars: "雷锋昨背洒汗温暖" },
    { title: "6", chars: "桌尝买具甘汁甜菜劳应" },
    { title: "7", chars: "弱周末母吸芬芳递勇敢" },
    { title: "语文园地二", chars: "程术服务" },
    { title: "识字 1", chars: "神州华各族情谊齐" },
    { title: "识字 2", chars: "传统贴街扫龙艾全团真" },
    { title: "识字 3", chars: "甲骨觉品钱币与财" },
    { title: "识字 4", chars: "食茄烤鸭煮鸡蛋饭" },
    { title: "语文园地三", chars: "辣乎" },
    { title: "8", chars: "梦硬铅盒森结苹精灵流" },
    { title: "9", chars: "匹妹波纹恋舍求奔" },
    { title: "10", chars: "旁阿姨弟便教拼音" },
    { title: "语文园地四", chars: "坦克" },
    { title: "11", chars: "亡补牢劝丢助坏死" },
    { title: "12", chars: "室排而实候班哈举" },
    { title: "13", chars: "愿意麦伯刻突然掉" },
    { title: "语文园地五", chars: "商厦洞穴" },
    { title: "14", chars: "窗含岭泊吴净莲映" },
    { title: "15", chars: "乌黑沉压响新迎扑" },
    { title: "16", chars: "指南针帮忠导永夜特积" },
    { title: "17", chars: "航宇宙或浴桶" },
    { title: "语文园地六", chars: "馆所" },
    { title: "18", chars: "扇慢遇定病睡根痛" },
    { title: "19", chars: "店决需付夫终期" },
    { title: "20", chars: "蛙卖搬倒泉砍破泳" },
    { title: "21", chars: "仿佛并任何纺织迟" },
    { title: "语文园地七", chars: "校内" },
    { title: "22", chars: "射最始换值弓炎此" },
    { title: "23", chars: "忽件启召众完却供" },
    { title: "24", chars: "治洪姓带必须仍继续业" },
    { title: "语文园地八", chars: "灿烂" }
];
