window.lessonData = [
    { title: "1 古诗二首", chars: "诗碧妆绿丝剪童归" },
    { title: "2 找春天", chars: "冲寻眉吐闻柳荡桃" },
    { title: "3 开满鲜花的小路", chars: "鲜原叔通巧惊礼" },
    { title: "4 邓小平爷爷植树", chars: "邓植格引注满" },
    { title: "语文园地一", chars: "剧场" },
    { title: "5 雷锋叔叔，你在哪里", chars: "雷锋昨背洒汗温暖" },
    { title: "6 千人糕", chars: "桌尝买具甘汁甜菜劳应" },
    { title: "7 一匹出色的马", chars: "弱周末母吸芬芳递勇敢" },
    { title: "语文园地二", chars: "程术服务" },
    { title: "识字 1 神州谣", chars: "神州华各族情谊齐" },
    { title: "识字 2 传统节日", chars: "传统贴街扫龙艾全团真" },
    { title: "识字 3 “贝”的故事", chars: "甲骨觉品钱币与财" },
    { title: "识字 4 中国美食", chars: "食茄烤鸭煮鸡蛋饭" },
    { title: "语文园地三", chars: "辣乎" },
    { title: "8 彩色的梦", chars: "梦硬铅盒森结苹精灵流" },
    { title: "9 枫树上的喜鹊", chars: "匹妹波纹恋舍求奔" },
    { title: "10 沙滩上的童话", chars: "旁阿姨弟便教拼音" },
    { title: "语文园地四", chars: "坦克" },
    { title: "11 寓言二则", chars: "亡补牢劝丢助坏死" },
    { title: "12 玲玲的画", chars: "室排而实候班哈举" },
    { title: "13 画杨桃", chars: "愿意麦伯刻突然掉" },
    { title: "语文园地五", chars: "商厦洞穴" },
    { title: "14 古诗二首", chars: "窗含岭泊吴净莲映" },
    { title: "15 雷雨", chars: "乌黑沉压响新迎扑" },
    { title: "16 要是你在野外迷了路", chars: "指南针帮忠导永夜特积" },
    { title: "17 太空生活趣事多", chars: "航宇宙或浴桶" },
    { title: "语文园地六", chars: "馆所" },
    { title: "18 大象的耳朵", chars: "扇慢遇定病睡根痛" },
    { title: "19 蜘蛛开店", chars: "店决需付夫终期" },
    { title: "20 青蛙卖泥塘", chars: "蛙卖搬倒泉砍破泳" },
    { title: "21 小毛虫", chars: "仿佛并任何纺织迟" },
    { title: "语文园地七", chars: "校内" },
    { title: "22 羿射九日", chars: "射最始换值弓炎此" },
    { title: "23 祖先的摇篮", chars: "忽件启召众完却供" },
    { title: "24 当世界年纪还小的时候", chars: "治洪姓带必须仍继续业" },
    { title: "语文园地八", chars: "灿烂" }
];
